### PR TITLE
versioneer the project

### PR DESCRIPTION
**Pull request by adybbroe**
Signed-off-by: Adam Dybbroe <Adam.Dybbroe@smhi.se>

### CODE REVIEW

**Comment by djhoese** [comment]
versioneer is no longer maintained. See https://github.com/pytroll/satpy/pull/856 and the related issue for more information.

**Comment by adybbroe** [comment]
@djhoese I remember I had heard you talk about this, asked @mraspaud whether versioneer was still the way to go, but think we misunderstood each other, he said "for now" we still use versioneer. I needed something working now for this and followed the easy path I knew. I am reading your PR, not really yet understanding, but if you think it is doable (for me) to go along that setuptools_scm path I am happy to give it a try? Or perhaps I can wait till the Satpy PR is merged and endorsed?

**Comment by djhoese** [comment]
If you can wait until the Satpy PR for us to have a better understanding of setuptools_scm then that might be best. If you can't, versioneer will be good enough.

**Comment by mraspaud** [comment]
I'm closing this since we are now moving away from versioneer

**Pull request closed without merging**
